
package pe.edu.upeu.soap.ws.daoImpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import pe.edu.upeu.soap.ws.dao.ObjectFactory;
import pe.edu.upeu.soap.ws.dao.Ventas;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VentasDao", targetNamespace = "http://dao.ws.soap.upeu.edu.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VentasDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns pe.edu.upeu.soap.ws.dao.Ventas
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readVenta", targetNamespace = "http://dao.ws.soap.upeu.edu.pe/", className = "pe.edu.upeu.soap.ws.dao.ReadVenta")
    @ResponseWrapper(localName = "readVentaResponse", targetNamespace = "http://dao.ws.soap.upeu.edu.pe/", className = "pe.edu.upeu.soap.ws.dao.ReadVentaResponse")
    @Action(input = "http://dao.ws.soap.upeu.edu.pe/VentasDao/readVentaRequest", output = "http://dao.ws.soap.upeu.edu.pe/VentasDao/readVentaResponse")
    public Ventas readVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
